"""empty message

Revision ID: 127615938ac0
Revises: 86f24dec59b5
Create Date: 2021-06-21 10:20:37.643586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127615938ac0'
down_revision = '86f24dec59b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
